add more allowed file types
jboucly/MMM-FTP-image pull request #6
Opened 2023-01-20 21:11 UTC by chansizzle

I forgot to include this in the last PR. All of these file types were tested. svg file type does not work, so it is not included in the authorized image types. It might be good to add toLowerCase() method to change all file type names to lowercase instead of 'jpg|JPG....'

2023-01-20 22:27 UTC, jboucly commented
Yes I agree as well make a `constant` which would be an array that would contain all the file extensions !

Example : 
```javascript
const extensions = ['png', 'jpg' ...];
extensions.map(e => e.toUpperCase()).join('|').concat(`|${extensions.join('|')}`)
```

2023-01-20 22:28 UTC, jboucly requested changes

2023-01-20 22:28 UTC, jboucly commented on node_helper.js
> +	imgAuthorized: 'png|PNG|jpg|JPG|jpeg|JPEG|gif|GIF|bmp|BMP|webp|WEBP|ico|ICO|dib|DIB',
Change this with coment in pr pls

2023-01-20 22:53 UTC, chansizzle commented
Just to be certain of clarity, uppercase extensions do not display on screen. Only extensions with lowercase extensions are displayed on screen. Uppercase file extensions and extensions that are not allowed both are ignored.

2023-01-24 10:31 UTC, jboucly commented
> Par souci de clarté, les extensions en majuscules ne s'affichent pas à l'écran. Seules les extensions avec des extensions en minuscules sont affichées à l'écran. Les extensions de fichiers en majuscules et les extensions non autorisées sont ignorées.

I'm not sure I understand :thinking:

2023-01-24 16:38 UTC, chansizzle commented
Disregard my last comment. The example you provided of creating a constant and an array looks like it will work perfectly.

2023-02-27 20:26 UTC, closed without merging

2023-02-27 20:27 UTC, jboucly commented
Hello @chansizzle ! 

I pushed the modifications for the extensions accepted! Thanks again for your participation!